INFO:pymorphy2.opencorpora_dict.wrapper:Loading dictionaries from /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/pymorphy2_dicts_ru/data
INFO:pymorphy2.opencorpora_dict.wrapper:format: 2.4, revision: 417127, updated: 2020-10-11T15:05:51.070345
INFO:pymorphy2.opencorpora_dict.wrapper:Loading dictionaries from /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/pymorphy2_dicts_ru/data
INFO:pymorphy2.opencorpora_dict.wrapper:format: 2.4, revision: 417127, updated: 2020-10-11T15:05:51.070345
INFO:aiogram:Bot: Promo Bot [@promoBotBashBot]
WARNING:aiogram:Goodbye!
INFO:pymorphy2.opencorpora_dict.wrapper:Loading dictionaries from /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/pymorphy2_dicts_ru/data
INFO:pymorphy2.opencorpora_dict.wrapper:format: 2.4, revision: 417127, updated: 2020-10-11T15:05:51.070345
INFO:aiogram:Bot: Promo Bot [@promoBotBashBot]
WARNING:aiogram:Goodbye!
wrapper.py [LINE:16] #INFO     [2022-11-23 22:33:20,063]  Loading dictionaries from /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/pymorphy2_dicts_ru/data
wrapper.py [LINE:20] #INFO     [2022-11-23 22:33:20,217]  format: 2.4, revision: 417127, updated: 2020-10-11T15:05:51.070345
executor.py [LINE:362] #INFO     [2022-11-23 22:33:21,178]  Bot: Promo Bot [@promoBotBashBot]
executor.py [LINE:329] #WARNING  [2022-11-23 22:33:21,179]  Goodbye!
wrapper.py [LINE:16] #INFO     [2022-11-23 22:34:20,657]  Loading dictionaries from /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/pymorphy2_dicts_ru/data
wrapper.py [LINE:20] #INFO     [2022-11-23 22:34:20,773]  format: 2.4, revision: 417127, updated: 2020-10-11T15:05:51.070345
executor.py [LINE:362] #INFO     [2022-11-23 22:34:21,797]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-23 22:34:21,797]  Start polling.
handlers.py [LINE:38] #INFO     [2022-11-23 22:36:21,958]  хай Wed Nov 23 22:36:21 2022
handlers.py [LINE:38] #INFO     [2022-11-23 22:36:38,725]  Сколько роботов? Wed Nov 23 22:36:38 2022
handlers.py [LINE:38] #INFO     [2022-11-23 22:36:50,276]  Да Wed Nov 23 22:36:50 2022
dispatcher.py [LINE:433] #INFO     [2022-11-23 23:58:12,451]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-23 23:58:12,452]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 13:11:12,891]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 13:11:12,899]  Start polling.
handlers.py [LINE:41] #INFO     [2022-11-25 13:11:13,486]  cumandir: Бот - Fri Nov 25 13:11:13 2022
handlers.py [LINE:41] #INFO     [2022-11-25 13:11:28,627]  cumandir: Привет - Fri Nov 25 13:11:28 2022
dispatcher.py [LINE:433] #INFO     [2022-11-25 13:11:40,711]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 13:11:40,719]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 13:13:15,966]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 13:13:15,967]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 13:13:29,789]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'Result' object has no attribute 'fetchone'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 39, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in get_answer
    return await answer_obj.get_answer(question.lower())
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 52, in select_answer_by_question
    return str(tuple(await self.cur.fetchone())[0])
AttributeError: 'Result' object has no attribute 'fetchone'
base_events.py [LINE:1744] #ERROR    [2022-11-25 13:13:52,529]  Task exception was never retrieved
future: <Task finished name='Task-13' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'Result' object has no attribute 'fetchone'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 39, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in get_answer
    return await answer_obj.get_answer(question.lower())
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 52, in select_answer_by_question
    return str(tuple(await self.cur.fetchone())[0])
AttributeError: 'Result' object has no attribute 'fetchone'
base_events.py [LINE:1744] #ERROR    [2022-11-25 13:13:54,163]  Task exception was never retrieved
future: <Task finished name='Task-16' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'Result' object has no attribute 'fetchone'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 39, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in get_answer
    return await answer_obj.get_answer(question.lower())
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 52, in select_answer_by_question
    return str(tuple(await self.cur.fetchone())[0])
AttributeError: 'Result' object has no attribute 'fetchone'
base_events.py [LINE:1744] #ERROR    [2022-11-25 13:14:00,019]  Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'Result' object has no attribute 'fetchone'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 39, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in get_answer
    return await answer_obj.get_answer(question.lower())
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 52, in select_answer_by_question
    return str(tuple(await self.cur.fetchone())[0])
AttributeError: 'Result' object has no attribute 'fetchone'
dispatcher.py [LINE:433] #INFO     [2022-11-25 13:25:22,959]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 13:25:22,960]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 13:26:17,731]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 13:26:17,732]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 13:26:30,321]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'Result' object has no attribute 'fetchone'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 39, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in get_answer
    return await answer_obj.get_answer(question.lower())
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 57, in select_answer_by_question
    return str(tuple(await self.cur.fetchone())[0])
AttributeError: 'Result' object has no attribute 'fetchone'
dispatcher.py [LINE:433] #INFO     [2022-11-25 13:27:55,741]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 13:27:55,742]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 13:28:34,994]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 13:28:34,996]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-25 13:31:12,800]  Stop polling...
executor.py [LINE:362] #INFO     [2022-11-25 13:31:36,236]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 13:31:36,239]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 13:32:01,472]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('LIMIT clause should come after UNION not before')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 39, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in get_answer
    return await answer_obj.get_answer(question.lower())
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 56, in select_answer_by_question
    self.cur = await self.con.execute(select_answer, (question, ))
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: LIMIT clause should come after UNION not before
dispatcher.py [LINE:433] #INFO     [2022-11-25 13:33:20,123]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 13:33:20,128]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 13:35:47,445]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 13:35:47,446]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-25 13:36:03,507]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 13:36:03,507]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:16:33,494]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:16:33,501]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:17:01,002]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'_UnixSelectorEventLoop' object has no attribute 'run_until_comlete'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    keyboard = await get_potential_keyboard()
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 67, in get_potential_keyboard
    buttons_obj = answer_obj.loop.run_until_comlete(ButtonCreator(answer_obj.potential_question_from_db_dict))
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'run_until_comlete'
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:17:50,284]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:17:50,286]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:18:08,504]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:18:08,505]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:18:55,873]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'_UnixSelectorEventLoop' object has no attribute 'run_until_comlete'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    keyboard = await get_potential_keyboard()
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 67, in get_potential_keyboard
    buttons_obj = answer_obj.loop.run_until_comlete(ButtonCreator(answer_obj.potential_question_from_db_dict))
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'run_until_comlete'
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:20:08,844]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:20:08,848]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:20:53,162]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:20:53,163]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:21:26,324]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'_UnixSelectorEventLoop' object has no attribute 'run_until_comlete'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    keyboard = await get_potential_keyboard()
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 67, in get_potential_keyboard
    buttons_obj = answer_obj.loop.run_until_comlete(ButtonCreator(answer_obj.potential_question_from_db_dict))
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'run_until_comlete'
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:22:07,238]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:22:07,248]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:22:19,262]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:22:19,264]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:22:59,711]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 46, in answer_handler
    await message.answer("Может быть, вы хотите задать один из этих вопросов:", reply_markup=keyboard)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:25:50,096]  Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 46, in answer_handler
    await message.answer("Может быть, вы хотите задать один из этих вопросов:", reply_markup=keyboard)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:26:13,343]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:26:13,347]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:26:25,511]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:26:25,513]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:27:53,469]  Stop polling...
executor.py [LINE:362] #INFO     [2022-11-25 23:28:04,434]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:28:04,436]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:28:21,540]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 46, in answer_handler
    await message.answer("Может быть, вы хотите задать один из этих вопросов:", reply_markup=keyboard)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:30:10,819]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:30:10,822]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:31:40,806]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:31:40,807]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:31:41,263]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=ProgrammingError('Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 51, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 22, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 34, in _choose_question
    question_list_from_db = await self.db.select_question_dict_like_tag_list(tag_list=tag_list)
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 49, in select_question_dict_like_tag_list
    self.cur = await self.con.execute(select_like,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:32:22,296]  Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=ProgrammingError('Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 51, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 22, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 34, in _choose_question
    question_list_from_db = await self.db.select_question_dict_like_tag_list(tag_list=tag_list)
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 49, in select_question_dict_like_tag_list
    self.cur = await self.con.execute(select_like,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:35:51,661]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:35:51,665]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:36:50,355]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:36:50,355]  Start polling.
handlers.py [LINE:47] #INFO     [2022-11-25 23:37:14,726]  cumandir: сколько - Fri Nov 25 23:37:14 2022
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:38:42,207]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:38:42,208]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:56:43,705]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:56:43,707]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:57:58,202]  Stop polling...
executor.py [LINE:362] #INFO     [2022-11-25 23:58:04,932]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:58:04,933]  Start polling.
handlers.py [LINE:58] #INFO     [2022-11-25 23:58:05,532]  cumandir: Сколкьо роботов - Fri Nov 25 23:58:05 2022
handlers.py [LINE:58] #INFO     [2022-11-25 23:58:12,469]  cumandir: Хай - Fri Nov 25 23:58:12 2022
handlers.py [LINE:58] #INFO     [2022-11-25 23:58:15,242]  cumandir: Привет - Fri Nov 25 23:58:15 2022
handlers.py [LINE:58] #INFO     [2022-11-25 23:58:19,600]  cumandir: эй - Fri Nov 25 23:58:19 2022
handlers.py [LINE:58] #INFO     [2022-11-25 23:58:23,670]  cumandir: ладно - Fri Nov 25 23:58:23 2022
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:58:54,649]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:58:54,650]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:59:02,070]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:59:02,071]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-25 23:59:04,449]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 52, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 62, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 22, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    for question_id, question_text in question_list_from_db.items():
AttributeError: 'NoneType' object has no attribute 'items'
dispatcher.py [LINE:433] #INFO     [2022-11-25 23:59:07,925]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-25 23:59:07,926]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-25 23:59:23,780]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-25 23:59:23,780]  Start polling.
handlers.py [LINE:58] #INFO     [2022-11-26 00:00:18,222]  cumandir: А сейчас - Sat Nov 26 00:00:18 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:03:14,810]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:03:14,811]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:06:38,585]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:06:38,586]  Start polling.
dispatcher.py [LINE:390] #ERROR    [2022-11-26 00:08:02,462]  Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [None]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [None]
base_events.py [LINE:1744] #ERROR    [2022-11-26 00:08:02,927]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 52, in answer_handler
    await message.answer("Мои вопросы", reply_markup=keyboard)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:09:24,990]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:09:24,993]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:09:37,822]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:09:37,824]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 00:10:16,014]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 52, in answer_handler
    await message.answer(text="Мои вопросы", reply_markup=keyboard)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
base_events.py [LINE:1744] #ERROR    [2022-11-26 00:21:47,291]  Task exception was never retrieved
future: <Task finished name='Task-49' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 52, in answer_handler
    keyboard = await get_potential_keyboard()
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:21:56,280]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:21:56,284]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:22:17,960]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:22:17,961]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:24:11,492]  cumandir: Првиет - Sat Nov 26 00:24:11 2022
base_events.py [LINE:1744] #ERROR    [2022-11-26 00:24:31,597]  Task exception was never retrieved
future: <Task finished name='Task-16' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 67, in send_random_value
    answer = await get_answer(question=call.message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 72, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 22, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    for question_id, question_text in question_list_from_db.items():
AttributeError: 'NoneType' object has no attribute 'items'
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:25:33,139]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:25:33,143]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:26:30,496]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:26:30,497]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:26:39,152]  cumandir: Привет - Sat Nov 26 00:26:39 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:28:53,668]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:28:53,669]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:29:03,184]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:29:03,185]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:29:06,355]  cumandir: хай - Sat Nov 26 00:29:06 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:32:09,415]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:32:09,416]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:32:14,341]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:32:14,342]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:32:25,853]  cumandir: 🥰 - Sat Nov 26 00:32:25 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:35:35,525]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:35:35,526]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:35:46,544]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:35:46,545]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:35:53,542]  cumandir: привет - Sat Nov 26 00:35:53 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:36:15,000]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:36:15,002]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:38:05,806]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:38:05,807]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:38:14,249]  cumandir: Один - Sat Nov 26 00:38:14 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:48:10,273]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:48:10,274]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:48:52,289]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:48:52,289]  Start polling.
handlers.py [LINE:62] #INFO     [2022-11-26 00:48:53,005]  cumandir: 😁 - Sat Nov 26 00:48:53 2022
handlers.py [LINE:62] #INFO     [2022-11-26 00:56:55,727]  cumandir: сколько - Sat Nov 26 00:56:55 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 00:57:00,007]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 00:57:00,009]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 00:59:20,983]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 00:59:20,984]  Start polling.
handlers.py [LINE:59] #INFO     [2022-11-26 00:59:44,867]  cumandir: Сколько - Sat Nov 26 00:59:44 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:00:07,509]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:00:07,510]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:03:29,273]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:03:29,274]  Start polling.
handlers.py [LINE:61] #INFO     [2022-11-26 01:03:39,123]  cumandir: сколько роботов - Sat Nov 26 01:03:39 2022
handlers.py [LINE:61] #INFO     [2022-11-26 01:04:01,425]  cumandir: сколько - Sat Nov 26 01:04:01 2022
handlers.py [LINE:61] #INFO     [2022-11-26 01:04:37,654]  cumandir: сколько роботов в штате? - Sat Nov 26 01:04:37 2022
handlers.py [LINE:61] #INFO     [2022-11-26 01:06:20,872]  cumandir: пачиму - Sat Nov 26 01:06:20 2022
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:12:03,500]  Task exception was never retrieved
future: <Task finished name='Task-76' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=ProgrammingError('Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 54, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 71, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 22, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 34, in _choose_question
    question_list_from_db = await self.db.select_question_dict_like_tag_list(tag_list=tag_list)
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 49, in select_question_dict_like_tag_list
    self.cur = await self.con.execute(select_like,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:16:31,389]  Task exception was never retrieved
future: <Task finished name='Task-94' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 40, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 77, in remember_user
    is_new_client = True
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:16:35,485]  Task exception was never retrieved
future: <Task finished name='Task-97' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 40, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 77, in remember_user
    is_new_client = True
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:16:36,885]  Task exception was never retrieved
future: <Task finished name='Task-100' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 40, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 77, in remember_user
    is_new_client = True
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:17:00,226]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:17:00,227]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:17:31,395]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:17:31,396]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:17:46,965]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 40, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 79, in remember_user
    await answer_obj.db.add_user(
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:18:52,433]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:18:52,434]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:19:10,846]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:19:10,848]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:19:12,272]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user(
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:21:08,506]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:21:08,508]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:21:19,692]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:21:19,693]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:21:20,163]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "FROM": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 79, in remember_user
    if not await answer_obj.db.check_user_by_id(user_data['user_id']):
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 68, in check_user_by_id
    self.cur = await self.con.execute('SELECT FROM clients WHERE user_id = ?', (user_id,))
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "FROM": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:22:01,456]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:22:01,459]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:22:11,885]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:22:11,887]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:22:40,754]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "FROM": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 79, in remember_user
    if not await answer_obj.db.check_user_by_id(user_data['user_id']):
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 68, in check_user_by_id
    self.cur = await self.con.execute('SELECT FROM clients WHERE user_id = ?', (user_id,))
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "FROM": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:23:33,235]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:23:33,240]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:26:13,651]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:26:13,653]  Start polling.
dispatcher.py [LINE:390] #ERROR    [2022-11-26 01:27:36,920]  Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [Errno 32] Broken pipe
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:27:36,951]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user(
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:28:40,561]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:28:40,565]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:29:37,478]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:29:37,479]  Start polling.
dispatcher.py [LINE:390] #ERROR    [2022-11-26 01:30:55,722]  Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ServerDisconnectedError: Server disconnected
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:30:55,736]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user(
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 72, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:35:58,392]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:35:58,396]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:36:07,477]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:36:07,478]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:37:07,134]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user(
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 73, in add_user
    self.cur = await self.con.execute('INSERT OR IGNORE clients VALUES (?, ?, ?)',
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:45:51,231]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:45:51,236]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:46:00,166]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:46:00,167]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 01:46:41,442]  Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user({
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 70, in add_user
    self.cur = await self.con.execute(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 01:47:46,905]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 01:47:46,908]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 01:48:03,148]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 01:48:03,149]  Start polling.
dispatcher.py [LINE:390] #ERROR    [2022-11-26 02:02:45,104]  Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
base_events.py [LINE:1744] #ERROR    [2022-11-26 02:02:45,128]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "clients": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user({
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 70, in add_user
    self.cur = await self.con.execute(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "clients": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 02:07:04,974]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 02:07:04,978]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 02:07:16,309]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 02:07:16,310]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 02:07:28,944]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('near "(": syntax error')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user({
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 70, in add_user
    self.cur = await self.con.execute(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "(": syntax error
dispatcher.py [LINE:433] #INFO     [2022-11-26 02:10:51,848]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 02:10:51,851]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 02:20:51,323]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 02:20:51,324]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-26 02:21:00,462]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('table clients has 4 columns but 3 values were supplied')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 41, in start_handler
    is_new_client = await remember_user(user_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 80, in remember_user
    await answer_obj.db.add_user({
  File "/home/sergey/PycharmProjects/promoBotBashBot/db_files/database.py", line 70, in add_user
    self.cur = await self.con.execute(
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table clients has 4 columns but 3 values were supplied
dispatcher.py [LINE:433] #INFO     [2022-11-26 02:21:36,877]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 02:21:36,881]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 02:21:51,944]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 02:21:51,946]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 02:24:45,304]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 02:24:45,316]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 02:25:02,922]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 02:25:02,923]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 02:25:25,986]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 02:25:25,988]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 22:36:14,683]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 22:36:14,691]  Start polling.
handlers.py [LINE:63] #INFO     [2022-11-26 22:36:45,008]  cumandir: Почему - Sat Nov 26 22:36:45 2022
dispatcher.py [LINE:433] #INFO     [2022-11-26 22:41:20,043]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 22:41:20,045]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-26 22:42:49,768]  Bot: Promo Bot [@promoBotBashBot]
dispatcher.py [LINE:358] #INFO     [2022-11-26 22:42:49,769]  Start polling.
dispatcher.py [LINE:433] #INFO     [2022-11-26 22:43:14,860]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-26 22:43:14,862]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 03:01:04,012]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 03:01:04,020]  start up bot - Sun Nov 27 03:01:04 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 03:01:04,020]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-27 03:01:04,630]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=OperationalError('no such table: dialog_table')>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 20, in get_answer
    answer = await self.find_answer_by_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 27, in find_answer_by_question
    return await self.db.select_answer_by_question(question+"?")
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/database.py", line 55, in select_answer_by_question
    self.cur = await self.con.execute(select_answer, (question,))
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: no such table: dialog_table
dispatcher.py [LINE:433] #INFO     [2022-11-27 03:01:11,221]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 03:01:11,223]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 03:05:21,763]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 03:05:21,764]  start up bot - Sun Nov 27 03:05:21 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 03:05:21,764]  Start polling.
handlers.py [LINE:54] #INFO     [2022-11-27 03:06:02,225]  cumandir: Сколько роботов - Sun Nov 27 03:06:02 2022
dispatcher.py [LINE:433] #INFO     [2022-11-27 03:06:29,128]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 03:06:29,129]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 04:15:38,802]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 04:15:38,803]  start up bot - Sun Nov 27 04:15:38 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 04:15:38,804]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:15:52,549]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    for question_id, question_text in question_list_from_db.items():
AttributeError: 'NoneType' object has no attribute 'items'
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:19:28,343]  Task exception was never retrieved
future: <Task finished name='Task-24' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    for question_id, question_text in question_list_from_db.items():
AttributeError: 'NoneType' object has no attribute 'items'
dispatcher.py [LINE:433] #INFO     [2022-11-27 04:20:13,910]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 04:20:13,914]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 04:20:23,760]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 04:20:23,761]  start up bot - Sun Nov 27 04:20:23 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 04:20:23,762]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:20:31,005]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    for question_id, question_text in question_list_from_db.items():
AttributeError: 'NoneType' object has no attribute 'items'
dispatcher.py [LINE:433] #INFO     [2022-11-27 04:20:37,364]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 04:20:37,369]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 04:21:03,914]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 04:21:03,915]  start up bot - Sun Nov 27 04:21:03 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 04:21:03,916]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:21:27,558]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'items'")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    for question_id, question_text in question_list_from_db.items():
AttributeError: 'NoneType' object has no attribute 'items'
dispatcher.py [LINE:433] #INFO     [2022-11-27 04:21:37,403]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 04:21:37,407]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 04:23:57,599]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 04:23:57,600]  start up bot - Sun Nov 27 04:23:57 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 04:23:57,601]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:23:58,556]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("'async for' requires an object with __aiter__ method, got coroutine")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    async for question_id, question_text in self.db.select_question_dict_like_tag_list(tag_list=tag_list):
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:24:28,408]  Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("'async for' requires an object with __aiter__ method, got coroutine")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    async for question_id, question_text in self.db.select_question_dict_like_tag_list(tag_list=tag_list):
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
dispatcher.py [LINE:433] #INFO     [2022-11-27 04:25:08,760]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 04:25:08,763]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 04:25:29,059]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 04:25:29,060]  start up bot - Sun Nov 27 04:25:29 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 04:25:29,061]  Start polling.
base_events.py [LINE:1744] #ERROR    [2022-11-27 04:25:33,867]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("'async for' requires an object with __aiter__ method, got coroutine")>
Traceback (most recent call last):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sergey/PycharmProjects/promoBotBashBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 45, in answer_handler
    answer = await get_answer(question=message.text)
  File "/home/sergey/PycharmProjects/promoBotBashBot/controllers/handlers.py", line 64, in get_answer
    return await answer_obj.get_answer(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 23, in get_answer
    question_from_db_id = await self._choose_question(question)
  File "/home/sergey/PycharmProjects/promoBotBashBot/models/answer_logic.py", line 37, in _choose_question
    async for question_id, question_text in self.db.select_question_dict_like_tag_list(tag_list=tag_list):
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
dispatcher.py [LINE:433] #INFO     [2022-11-27 04:29:23,296]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 04:29:23,299]  Goodbye!
executor.py [LINE:362] #INFO     [2022-11-27 04:29:42,998]  Bot: Promo Bot [@promoBotBashBot]
handlers.py [LINE:21] #INFO     [2022-11-27 04:29:42,999]  start up bot - Sun Nov 27 04:29:42 2022
dispatcher.py [LINE:358] #INFO     [2022-11-27 04:29:43,000]  Start polling.
handlers.py [LINE:54] #INFO     [2022-11-27 04:30:21,405]  cumandir: Сколько - Sun Nov 27 04:30:21 2022
handlers.py [LINE:54] #INFO     [2022-11-27 04:30:42,915]  cumandir: кладовая - Sun Nov 27 04:30:42 2022
dispatcher.py [LINE:433] #INFO     [2022-11-27 04:32:41,324]  Stop polling...
executor.py [LINE:329] #WARNING  [2022-11-27 04:32:41,333]  Goodbye!
